version: '3.4'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  broker:
    image: confluentinc/cp-kafka:7.3.2
    hostname: broker
    container_name: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./data/broker/data:/var/lib/broker/data
  
  clickhouse-node1:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse-node1
    hostname: clickhouse-node1
    volumes:
      - ./data/db/node1:/etc/clickhouse-server

  clickhouse-node2:
    image: yandex/clickhouse-server:20.3
    container_name: clickhouse-node2
    hostname: clickhouse-node2
    volumes:
      - ./data/db/node2:/etc/clickhouse-server

  etl:
    build: 
      context: ./.
      dockerfile: src/etl/Dockerfile
    env_file:
      - ./.env

  fastapi:
    build: 
      context: ./.
      dockerfile: src/api/Dockerfile
    env_file:
      - ./.env
