version: '3.4'
services:

  zookeeper:
    extends:
      file: docker-compose-base.yml
      service: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./test_data/zookeeper/data:/test_data
      - ./test_data/zookeeper/datalog:/test_datalog

  broker:
    extends:
      file: docker-compose-base.yml
      service: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - ./test_data/broker/data:/var/lib/broker/test_data

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:29092
    depends_on:
      - broker

  clickhouse-node1:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node1
    ports:
      - "8123:8123"
    depends_on:
      - zookeeper
      - broker

  clickhouse-node2:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node2
    depends_on:
      - zookeeper
      - broker

  fastapi:
    extends:
      file: docker-compose-base.yml
      service: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - broker