version: '3.4'
services:

  zookeeper:
    extends:
      file: docker-compose-base.yml
      service: zookeeper

  nginx:
    extends:
      file: docker-compose-base.yml
      service: nginx
    depends_on:
      - logstash

  broker:
    extends:
      file: docker-compose-base.yml
      service: broker
    depends_on:
      - zookeeper

  clickhouse-node1:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node1
    depends_on:
      - zookeeper

  clickhouse-node2:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node2
    depends_on:
      - zookeeper

  mongo:
    extends:
      file: docker-compose-base.yml
      service: mongo
    expose:
      - "${DB_PORT}"

  mongo-express:
    extends:
      file: docker-compose-base.yml
      service: mongo-express
    expose:
      - "${ME_PORT}"

  fastapi:
    extends:
      file: docker-compose-base.yml
      service: fastapi
    depends_on:
      - mongo
      - broker

  elasticsearch:
    extends:
      file: docker-compose-base.yml
      service: elasticsearch
    expose:
      - "${ES_PORT}"

  logstash:
    extends:
      file: docker-compose-base.yml
      service: logstash
    volumes:
      - /tmp/logs/nginx/:/var/log/nginx/:ro
    expose:
      - "${LS_PORT}"

  kibana:
    extends:
      file: docker-compose-base.yml
      service: kibana
    expose:
      - "${KB_PORT}"
    depends_on:
      - elasticsearch

  filebeat:
    extends:
      file: docker-compose-base.yml
      service: filebeat
    depends_on:
      - fastapi
      - nginx
      - logstash
      - elasticsearch
      - kibana
    links:
      - logstash

  jaeger:
    extends:
      file: docker-compose-base.yml
      service: jaeger
    depends_on:
      - fastapi