name: Проверка
on: [push]
jobs:
  linter:
    name: Линтер
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install flake8==6.0.0 black==23.3.0 isort==5.12.0 mypy==1.3.0
    - name: Запуск линтеров
      run: make linters
